### ISSUE TITLE
大佬，能否写一个自动同步你这个项目的脚本

### ISSUE THREAD

**Issue by ye1314** [simo8102/88-AutoSignMachine#140]
您好，您这边能否弄一个自动同步你这上游的脚本可以吗？因为上游变化了，我这边要删除项目，再fork项目，重新添加secret比较麻烦

**Comment by SpoonerCake** [comment]
对，就是repo_sync

**Comment by tanzl** [comment]
你可以自己安装[pull](https://github.com/apps/pull)这个插件啊

**Comment by lxr760** [comment]
> 你可以自己安装[pull](https://github.com/apps/pull)这个插件啊

装了pull以后要设置吗  ？

**Comment by tanzl** [comment]
> > 你可以自己安装[pull](https://github.com/apps/pull)这个插件啊
> 
> 装了pull以后要设置吗 ？

基本上不需要，想改可以看官方文档。

**Comment by simo8102** [comment]
![QQ截图20210416194938](https://user-images.githubusercontent.com/45913291/115020351-1152aa00-9eed-11eb-9e55-620c196382f0.png)
![QQ截图20210416194956](https://user-images.githubusercontent.com/45913291/115020358-13b50400-9eed-11eb-8371-44cb6b7b1508.png)
![QQ截图20210416195030](https://user-images.githubusercontent.com/45913291/115020367-157ec780-9eed-11eb-824b-79de1a970cbe.png)
只要你库得代码和我得库冲突不大都能拉到你得库

然后回到你自己得库
你会发现
![QQ截图20210416195200](https://user-images.githubusercontent.com/45913291/115020485-3d6e2b00-9eed-11eb-8a40-ed5e623c3c6b.png)
你得库这里会有一个合并请求  自己看清楚了同意合并就行

**Comment by xsp1343001800** [comment]
直接用pull。然后选择这个大佬的库。只要你自己不怎么改代码。就可以一直同步。

**Comment by simo8102** [comment]
此issue已经被添加了done标签且已经超过7天没有活跃，为了减少issue数量此issue将被自动关闭，如此issue问题仍未解决请手动重新打开本issue
            
            --------------------------------------------------------------------------------------- 来自 88-AutoSignMachine issues自动管理姬
