### ISSUE TITLE
actions 一直失败

### ISSUE THREAD

**Issue by sunmaojing** [simo8102/88-AutoSignMachine#142]
参数都是按照 简介里填写的 ，所得action都是 This check failed  。  这个该怎么处理呀

**Comment by sunmaojing** [comment]
value里的   难道需要用括号括起来？ 我现在没括起来

**Comment by simo8102** [comment]
请附上截图

**Comment by simo8102** [comment]
> 请附上截图

刚刚去你库看了下 好像是被GitHub拉黑了  你可以按他下面提示得去解决下

**Comment by sunmaojing** [comment]
> > 请附上截图
> 
> 刚刚去你库看了下 好像是被GitHub拉黑了 你可以按他下面提示得去解决下

我没看到 有什么解决提示呀。
