### ISSUE TITLE
本地运行，大家都用了几个小时？

### ISSUE THREAD

**Issue by keaimao1989** [simo8102/88-AutoSignMachine#162]
上午十点开始弄，接近5个小时了还在跑，手机是小米K30，cpu是765G，用的termux。

大家都花了几个小时本地运行完成了？

**Comment by simo8102** [comment]
程序建议在前台后台可能会被系统暂停

**Comment by keaimao1989** [comment]
> 程序建议在前台后台可能会被系统暂停

为了防止系统删后台，已经设置了自启动和电源管理控制
