### ISSUE TITLE
怎么删了actions啊

### ISSUE THREAD

**Issue by qw392281711** [simo8102/88-AutoSignMachine#163]
我用着挺好的，本地运行得开电脑，还得折腾下node，那玩意太魔性了，我电脑搞不定，用虚拟机反而没问题，这东西能部署到docker上面吗？我看评论好像有人可以，不过没回复我，大佬能简单说下docker方法吗？我前几天其实还折腾过腾讯云也失败了

**Comment by simo8102** [comment]
如果确实需要 等下恢复

**Comment by youppgd** [comment]
本地运行不太现实，太耗时了。

**Comment by Sumouruge2390** [comment]
同希望回复action运行，

**Comment by simo8102** [comment]
> 同希望回复action运行，

**Comment by simo8102** [comment]
已恢复

**Comment by simo8102** [comment]
此issue已经被添加了done标签且已经超过7天没有活跃，为了减少issue数量此issue将被自动关闭，如此issue问题仍未解决请手动重新打开本issue
            
            --------------------------------------------------------------------------------------- 来自 88-AutoSignMachine issues自动管理姬

**Comment by start0325** [comment]
请问为什么说

> 并非本人项目

我看了docker文件，没找到其他镜像的名字
