### ISSUE TITLE
积分抽奖消耗奖励积分

### ISSUE THREAD

**Issue by Sakananb** [simo8102/88-AutoSignMachine#176]
19号和20号都有
![Screenshot_2021-04-20-06-54-58-481_com sinovatech unicom ui](https://user-images.githubusercontent.com/80612444/115313237-79cbb080-a1a5-11eb-89ea-b9d9ac80b5e5.jpg)

**Comment by simo8102** [comment]
未发现相同情况

**Comment by xsp1343001800** [comment]
> 19号和20号都有
> ![Screenshot_2021-04-20-06-54-58-481_com sinovatech unicom ui](https://user-images.githubusercontent.com/80612444/115313237-79cbb080-a1a5-11eb-89ea-b9d9ac80b5e5.jpg)

我也遇到过。
我都是把积分抽奖和兑换积分给屏蔽了。之前我也反馈过。作者没有发现问题，又把积分抽奖恢复了。

**Comment by PDxtXHd** [comment]
我这边也没有复现过，觉得有问题的参考之前的修改自己注释一下代码吧
