### ISSUE TITLE
点击New repository secret后的操作是什么

### ISSUE THREAD

**Issue by qian9008** [simo8102/88-AutoSignMachine#71]
填密钥 名称
然后修改粘贴参数

 ENABLE_UNICOM （true）

unicom_password（服务密码）

unicom_user（手机号）

unicom_appid（*******）

**Comment by simo8102** [comment]
![QQ截图20210405175709](https://user-images.githubusercontent.com/45913291/113562255-60205a00-9638-11eb-88c8-d3be1f9cbb60.png)
以此类推

**Comment by qian9008** [comment]
终于可以了，之前用其他程序 ，密钥只要一个包含所有内容，所以理解错误了。谢谢！
